services:
    db:
        image: postgres:16
        container_name: pgsql_db
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: testdb
        ports:
            - "5434:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        restart: always

    pgweb:
        image: sosedoff/pgweb
        container_name: pgweb
        ports:
            - "8081:8081"
        environment:
            - DATABASE_URL=postgres://root:root@db:5432/testdb?sslmode=disable
        depends_on:
            - db

volumes:
    postgres_data:
